#!/usr/bin/env zsh

# Make a backup of preferences before or after changes were made.
#
# Usage:
# ./make_backup --before/--after [--root] [--help]
# ./make_backup -b/-a [-r] [-h]

source utils

before_or_after=""
root=""

for arg in ${@[@]}; do
	case ${arg} in
		(-b|--before)
			before_or_after=${PATH_BEFORE}
			;;
		(-a|--after)
			before_or_after=${PATH_AFTER}
			;;
		(-r|--root)
			root="root"
			;;
		(-h|--help)
			printf "Usage: ./make_backup --before/--after [--root]\n"
			exit 0
			;;
	esac
done

if [ -z ${before_or_after} ]; then
	println_colour red "No option was chosen, therefore no backups were made."
	println_colour red "Usage: ./make_backup --before/--after [--root]\n"
	exit 1
fi

destination="${before_or_after}"

if [ -z ${root} ]; then
	rm -rf ${destination}
	mkdir -p ${PATH_PREFERENCES_BACKUP} && cp -r ${PATH_PREFERENCES_USER} ${destination}
else
	rm -rf "${destination}_ROOT"
	mkdir -p ${PATH_PREFERENCES_BACKUP} && sudo cp -r ${PATH_PREFERENCES_ROOT} "${destination}_ROOT"
fi
