#!/usr/bin/env zsh

# Make a backup of preferences before and after changes are made.
#
# Usage:
# ./make_backup [before/after]

source utils

if [ -z ${1} ]; then
	vared -p "Is it a backup (${COLOUR_MAGENTA}b${TEXT_RESET})efore or (${COLOUR_MAGENTA}a${TEXT_RESET})fter the change was made? (${COLOUR_MAGENTA}before${TEXT_RESET}/${COLOUR_MAGENTA}after${TEXT_RESET}): " -c before_or_after
else
	before_or_after=${1}
fi

case ${before_or_after} in
	b|B|before|Before|BEFORE )
		destination=${PATH_BEFORE}
	;;
	a|A|after|After|AFTER )
		destination=${PATH_AFTER}
	;;
	* )
		println_colour red "No option was chosen, therefore no backups were made."
		exit 1
	;;
esac

mkdir -p ${PATH_PREFERENCES_BACKUP} && cp -r ~/Library/Preferences/ ${destination}
